# Generated by Django 5.1.2 on 2024-12-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='password2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
