# Generated by Django 5.1.2 on 2024-12-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiledata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='profiledata',
            name='password2',
        ),
    ]
