# Generated by Django 5.1.2 on 2024-12-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profiledata_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileData',
        ),
    ]
