# Generated by Django 4.2.17 on 2024-12-11 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0012_alter_post_user_alter_profiledata_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledata',
            name='post',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='data.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
