# Generated by Django 4.2.17 on 2024-12-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='user',
        ),
    ]
