# Generated by Django 4.2.17 on 2024-12-11 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_remove_profiledata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='post',
        ),
    ]
