# Generated by Django 4.2.17 on 2024-12-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_profiledata_post_profiledata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(default='', max_length=500),
        ),
    ]
