# Generated by Django 4.2.17 on 2024-12-13 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_alter_post_id_alter_profiledata_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='password',
            new_name='password2',
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='data.post'),
        ),
    ]
